# Generated by Django 2.2.6 on 2019-10-12 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('cpf', models.TextField(max_length=14)),
                ('foto', models.ImageField(upload_to='alunos/')),
            ],
        ),
        migrations.CreateModel(
            name='Conselho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('situacao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Aluno')),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Conselho')),
            ],
            options={
                'verbose_name': 'Votação',
                'verbose_name_plural': 'Votações',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('Aprovar', 'Aprovar'), ('Reprovar', 'Reprovar'), ('Abster', 'Abster')], default='Abster', max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Votacao')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioConselho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Conselho')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('sala', models.TextField(max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Turma')),
            ],
        ),
        migrations.AddField(
            model_name='conselho',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Turma'),
        ),
        migrations.CreateModel(
            name='AvaliacaoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('ano', models.PositiveIntegerField()),
                ('avaliacao', models.PositiveIntegerField(default=0)),
                ('outros_avaliacao', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('oferta_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.OfertaDisciplina')),
            ],
            options={
                'verbose_name': 'Avaliação de turma',
                'verbose_name_plural': 'Avaliações de turmas',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('avaliacao', models.PositiveIntegerField(default=0)),
                ('outros_avaliacao', models.TextField(blank=True, max_length=255, null=True)),
                ('ano', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Aluno')),
                ('oferta_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.OfertaDisciplina')),
            ],
            options={
                'verbose_name': 'Avaliação de aluno',
                'verbose_name_plural': 'Avaliações de alunos',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Turma'),
        ),
    ]
