# Generated by Django 2.1.7 on 2019-09-18 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('cpf', models.TextField(max_length=14)),
                ('foto', models.ImageField(upload_to='alunos/')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Aluno')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avaliação de aluno',
                'verbose_name_plural': 'Avaliações de alunos',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bimestre', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Avaliação de turma',
                'verbose_name_plural': 'Avaliações de turmas',
            },
        ),
        migrations.CreateModel(
            name='Conselho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('situacao', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField(max_length=30)),
                ('ano', models.IntegerField()),
                ('sala', models.TextField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Votacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.BooleanField(default=False)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Aluno')),
            ],
            options={
                'verbose_name': 'Votação',
                'verbose_name_plural': 'Votações',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(choices=[('Reprovar', 'Reprovar'), ('Abster', 'Abster'), ('Aprovar', 'Aprovar')], default='Abster', max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Votacao')),
            ],
        ),
        migrations.AddField(
            model_name='conselho',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Turma'),
        ),
        migrations.AddField(
            model_name='avaliacaoturma',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Turma'),
        ),
        migrations.AddField(
            model_name='avaliacaoturma',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacoes.Turma'),
        ),
    ]
