# Generated by Django 2.1.7 on 2019-09-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curso', models.TextField(max_length=30)),
                ('Ano', models.IntegerField()),
                ('Sala', models.TextField(max_length=1)),
            ],
        ),
    ]
