# Generated by Django 2.1.7 on 2019-09-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='situacao',
            field=models.CharField(choices=[('Reprovar', 'Reprovar'), ('Abster', 'Abster'), ('Aprovar', 'Aprovar')], default='Abster', max_length=8),
        ),
    ]
