# Generated by Django 2.1.7 on 2019-09-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='Situacao',
            field=models.CharField(choices=[('Abster', 'Abster'), ('Reprovar', 'Reprovar'), ('Aprovar', 'Aprovar')], default='Abster', max_length=8),
        ),
    ]
