# Generated by Django 2.1.7 on 2019-10-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='situacao',
            field=models.CharField(choices=[('Reprovar', 'Reprovar'), ('Aprovar', 'Aprovar'), ('Abster', 'Abster')], default='Abster', max_length=8),
        ),
    ]
