# Generated by Django 2.1.7 on 2019-09-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0002_auto_20190911_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Cpf',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='Turma',
            new_name='turma',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='Aluno',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='conselho',
            old_name='Data',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='conselho',
            old_name='Situacao',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='conselho',
            old_name='Turma',
            new_name='turma',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='Ano',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='Curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='Sala',
            new_name='sala',
        ),
        migrations.RenameField(
            model_name='votacao',
            old_name='Aluno',
            new_name='aluno',
        ),
        migrations.RenameField(
            model_name='votacao',
            old_name='Situacao',
            new_name='situacao',
        ),
        migrations.RenameField(
            model_name='voto',
            old_name='Usuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='voto',
            old_name='Votacao',
            new_name='votacao',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='Situacao',
        ),
        migrations.AddField(
            model_name='voto',
            name='situacao',
            field=models.CharField(choices=[('Abster', 'Abster'), ('Aprovar', 'Aprovar'), ('Reprovar', 'Reprovar')], default='Abster', max_length=8),
        ),
    ]
