# Generated by Django 2.2.6 on 2019-11-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0002_auto_20191030_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='alunos/default.png', upload_to='alunos/'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='situacao',
            field=models.CharField(choices=[('Abster', 'Abster'), ('Reprovar', 'Reprovar'), ('Aprovar', 'Aprovar')], default='Abster', max_length=8),
        ),
    ]
