# Generated by Django 2.2.6 on 2019-11-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0003_auto_20191031_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='media/default.png', upload_to='alunos/'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='situacao',
            field=models.CharField(choices=[('Aprovar', 'Aprovar'), ('Abster', 'Abster'), ('Reprovar', 'Reprovar')], default='Abster', max_length=8),
        ),
    ]
