# Generated by Django 2.2.6 on 2019-11-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0004_auto_20191031_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='situacao',
            field=models.CharField(choices=[('Abster', 'Abster'), ('Reprovar', 'Reprovar'), ('Aprovar', 'Aprovar')], default='Abster', max_length=8),
        ),
    ]
