# Generated by Django 2.2.6 on 2019-11-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacoes', '0006_auto_20191031_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='alunos/'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='situacao',
            field=models.CharField(choices=[('Aprovar', 'Aprovar'), ('Reprovar', 'Reprovar'), ('Abster', 'Abster')], default='Abster', max_length=8),
        ),
    ]
